spring:
  # ???????
  datasource:
    # ??????? MySQL 8.0+ ?????
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ????????localhost ?????3306 ????usv_simulation_db ???????
    url: jdbc:mysql://localhost:3306/usv_simulation_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    # ?????
    username: root
    # ???????????? MySQL ?????? ???
    password: 05960596

  # MyBatis ????????? SQL ????
  mybatis-plus:
    # ??????????????? Java ?
    type-aliases-package: com.hzk.backend.entity
    configuration:
      # ?????? SQL ??????????????????? SQL
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      # ???????????????? device_name ????? Java ?? deviceName?
      map-underscore-to-camel-case: true

# ????????? 8080
server:
  port: 8080